spring:
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=/identity-service/**
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=/profile-service/api/**
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notification-service/**
        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=/post-service/**