spring:
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=/identity-service/**
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=/profile-service/api/v1/accounts/**
